apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hello-world-uat-test
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: uat-test
    environment: stage-green
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-green
        path: ./uat-test
  workloadVersion:
    version: 0.0.1-31
    commit: 7d783a24f90ef47060d52c91ba8e5567f16898b7    