apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hw-perf-stage
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: hw-perf-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./hw-perf
  workloadVersion:
    version: 0.0.1-60
    commit: 6f347d04b216f5750b75e01bb015ea944e5b7998    
