apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hello-world-functional-test-dev-green
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: functional-test
    environment: dev-green
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-green
        path: ./functional-test
  workloadVersion:
    version: 0.0.1-36
    commit: 2da6a937fc1e1b79ff69c1b4d460a42c4a6ec72d    
