apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hello-world-functional-test-dev-gray
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: functional-test
    environment: dev-gray
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./functional-test
  workloadVersion:
    version: 0.0.1-37
    commit: b242048820048d40aebd7cbe6a46cf4b70606ace    
