---
# Source: hello-world/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-functional-service
      
  namespace: stage
      
spec:
  selector:
    app: hello-world-functional
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: hello-world/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-functional-deployment
  annotations:
    version: 0.0.1-1
      
  namespace: stage
      
spec:
  strategy: 
    type: Recreate      
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-functional
  template:
    metadata:
      labels:
        app: hello-world-functional      
      annotations:
        version: 0.0.1-1
    spec:
      containers:
      - name: hello-world-functional
        image: ghcr.io/eedorenko/hello-world/hello-world:0.0.1-1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: CLUSTER_NAME
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: CLUSTER_NAME
        - name: REGION
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: REGION
        - name: ENVIRONMENT
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: ENVIRONMENT
        - name: DATABASE_URL
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DATABASE_URL
