apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hw-stage-gray
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: hw-stage-gray
    environment: stage-gray
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage-gray
        path: ./hw
  workloadVersion:
    version: 0.0.1-53
    commit: 40fedad02e3e81afac02f6e8da5c4966074cb05a    
