apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hw-dev-gray
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: hw-dev-gray
    environment: dev-gray
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./hw
  workloadVersion:
    version: 0.0.1-41
    commit: 1030d8a6f36042d368e6290a8cd3b12a77f79115    
