apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hw-func-stage
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: hw-func-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./hw-func
  workloadVersion:
    version: 0.0.1-66
    commit: d70ea1aed6bf87032ca3ca25fa8acf82ac47ac9b    
