apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hw-func-stage
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: hw-func-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./hw-func
  workloadVersion:
    version: 0.0.1-61
    commit: 3915e5a7b1e944e819afc44c686d3d6d9103e07e    
