apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: perf-stage
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: perf-stage
    environment: stage
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: stage
        path: ./perf
  workloadVersion:
    version: 0.0.1-57
    commit: 234c25131c6e9e9033d7d3dd9b80fd6472092ef6    
