---
# Source: hello-world/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hello-world-functional-east-us-service
      
  namespace: dev-gray
      
spec:
  selector:
    app: hello-world-functional-east-us
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# Source: hello-world/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-functional-east-us-deployment
  annotations:
    version: 0.0.1-2
      
  namespace: dev-gray
      
spec:
  strategy: 
    type: Recreate      
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-functional-east-us
  template:
    metadata:
      labels:
        app: hello-world-functional-east-us      
      annotations:
        version: 0.0.1-2
    spec:
      containers:
      - name: hello-world-functional-east-us
        image: ghcr.io/eedorenko/hello-world/hello-world:0.0.1-2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: CLUSTER_NAME
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: CLUSTER_NAME
        - name: REGION
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: REGION
        - name: ENVIRONMENT
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: ENVIRONMENT
        - name: DATABASE_URL
          valueFrom:
              configMapKeyRef:
                name: platform-config
                key: DATABASE_URL
