apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: hello-world-functional-test-east-us-dev-gray
spec:
  workload:
    name: hw
    source:
        repo: https://github.com/eedorenko/hello-world
        branch: main
        path: .
    application:
        name: hello-world
        workspace:
            name: kaizen-team
  deploymentTarget:
    name: functional-test-east-us
    environment: dev-gray
    manifests:
        repo: https://github.com/eedorenko/hello-world-gitops
        branch: dev-gray
        path: ./functional-test/east-us
  workloadVersion:
    version: 0.0.1-34
    commit: 550ec125ca8fd7176d50afd2a1ae5a5f2e89e9ce    
